name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller --noconfirm --clean --onedir --windowed --name ACS-AI-Image-Reproducer app.py --icon compiler_workspace/app_icon.ico

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Windows-App
          path: dist/
